### ISSUE TITLE
Group Layers do not have an object

### ISSUE THREAD

**Issue by miltoncandelero** [Chnapy/tiled-types#1]
This is an example group

```json
        {
         "id":2,
         "layers":[...],
         "name":"group name here",
         "opacity":1,
         "type":"group",
         "visible":true,
         "x":0,
         "y":0
```

it should be quite simple 

```ts
export interface TiledLayerGrouplayer extends TiledLayerAbstract<'group'> {
         layers: Array<TiledLayer<any>>;
         type:"group",
}
```

Super strangled of time, can't test nor PR now, sorry :(

**Comment by Chnapy** [comment]
It would seem I have forgotten this type. I already have some fixes to do (optional properties), I think I'll fix this issue in the same time. I don't know when yet (like you I don't have much time).
Thanks for reporting this issue :+1:
